#! /usr/bin/env php

<?php

use App\AddCommand;
use App\CompleteTaskCommand;
use App\DatabaseAdapter;
use App\NewCommand;
use App\RenderCommand;
use App\ShowCommand;
use Symfony\Component\Console\Application;

require 'vendor/autoload.php';

$app = new Application('Laracasts Demo', '1.0');

$app->add(new NewCommand(new \GuzzleHttp\Client));
$app->add(new RenderCommand);

try {
    $pdo = new PDO('sqlite:db.sqlite');
    $pdo->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE, PDO::FETCH_ASSOC);
    $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
} catch (PDOException $e) {
    echo 'Could not connect to database';
    exit(1);
}

$dbAdapter = new DatabaseAdapter($pdo);
$app->add(new ShowCommand($dbAdapter));
$app->add(new AddCommand($dbAdapter));
$app->add(new CompleteTaskCommand($dbAdapter));

$app->run();